//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineResultCheckPortal
{
    using System;
    
    public partial class AdminUserProfileDisplay_Result1
    {
        public Nullable<long> RowNumber { get; set; }
        public long ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public string MobileNo { get; set; }
        public string EmailID { get; set; }
        public string City { get; set; }
        public Nullable<short> RoleID { get; set; }
        public Nullable<short> StateID { get; set; }
        public Nullable<short> CountryID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> CreatedByID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> UpdatedByID { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
