//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineResultCheckPortal
{
    using System;
    
    public partial class AdminUserProfileDisplay_Result27
    {
        public Nullable<long> RowNumber { get; set; }
        public string StudentID { get; set; }
        public int ID { get; set; }
        public string fullName { get; set; }
        public string Dob { get; set; }
        public string LocalGovernment { get; set; }
        public string SchoolName { get; set; }
        public string State { get; set; }
        public string Gender { get; set; }
        public Nullable<int> School { get; set; }
    }
}
