//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineResultCheckPortal
{
    using System;
    
    public partial class EditUserProfile_Result6
    {
        public Nullable<long> RowNumber { get; set; }
        public string RoleName { get; set; }
        public int ID { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailID { get; set; }
        public Nullable<short> RoleId { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string CreateDate { get; set; }
    }
}
