//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineResultCheckPortal
{
    using System;
    
    public partial class GetDetailsMockExamanation_Result3
    {
        public Nullable<long> RowNumber { get; set; }
        public int ID { get; set; }
        public Nullable<int> JSCEID { get; set; }
        public string TestName { get; set; }
        public string Marks { get; set; }
        public string Result { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string FileName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Session { get; set; }
        public Nullable<int> IsDeletedBy { get; set; }
        public Nullable<System.DateTime> IsDeletedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public int ID1 { get; set; }
        public Nullable<int> StundentID { get; set; }
        public string JSCERegNumber { get; set; }
        public Nullable<System.DateTime> CreatedDate1 { get; set; }
        public Nullable<int> CreatedBy1 { get; set; }
        public Nullable<bool> IsDeleted1 { get; set; }
    }
}
