//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineResultCheckPortal
{
    using System;
    
    public partial class GetDisplayListJSCEResult_Result1
    {
        public int ID { get; set; }
        public Nullable<int> JSCEID { get; set; }
        public string TestName { get; set; }
        public string Marks { get; set; }
        public string Result { get; set; }
        public string CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string FileName { get; set; }
        public string Description { get; set; }
        public string Session { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string DeletedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string UpdatedDate { get; set; }
    }
}
