//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineResultCheckPortal
{
    using System;
    
    public partial class GetDetailsMockExamanation_Result8
    {
        public Nullable<long> RowNumber { get; set; }
        public int ID { get; set; }
        public string RegistrationNumber { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public string ReportCardFile { get; set; }
        public string FullName { get; set; }
    }
}
