//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineResultCheckPortal
{
    using System;
    
    public partial class GetDisplayListJSCEResult_Result4
    {
        public Nullable<long> RowNumber { get; set; }
        public int ID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string TestName { get; set; }
        public Nullable<int> JSCEID { get; set; }
        public string Marks { get; set; }
        public string Session { get; set; }
        public string JSCERegNumber { get; set; }
        public string Result { get; set; }
    }
}
