//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineResultCheckPortal
{
    using System;
    
    public partial class GetEditMangement_Result9
    {
        public Nullable<long> RowNumber { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string RoleName { get; set; }
        public short RoleID { get; set; }
        public int UserId { get; set; }
        public bool IsActive { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailID { get; set; }
        public string Password { get; set; }
        public string FatherName { get; set; }
        public string Gender { get; set; }
        public string ContactNo { get; set; }
        public string Address { get; set; }
        public string DateofBirth { get; set; }
        public string Photo { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> IsApprovedBy { get; set; }
        public Nullable<int> IsDeletedBy { get; set; }
        public string CreateDate { get; set; }
    }
}
