//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineResultCheckPortal
{
    using System;
    
    public partial class GetManageJSCEEdit_Result1
    {
        public int ID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string FullName { get; set; }
        public Nullable<int> StundentID { get; set; }
        public string JSCERegNumber { get; set; }
        public string CreateDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int JSCEID { get; set; }
    }
}
