//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineResultCheckPortal
{
    using System;
    
    public partial class GetSchoolDetails_Result2
    {
        public Nullable<int> school { get; set; }
        public string SchoolName { get; set; }
        public string SchoolAddress { get; set; }
        public string Zone { get; set; }
        public string Zipcode { get; set; }
        public Nullable<int> AllCountSchool { get; set; }
    }
}
