//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineResultCheckPortal
{
    using System;
    
    public partial class GetStudentProfile_Result3
    {
        public Nullable<long> RowNumber { get; set; }
        public string SchoolName { get; set; }
        public int ID { get; set; }
        public string fullName { get; set; }
        public string EmailID { get; set; }
        public Nullable<short> RoleId { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> IsApprovedBy { get; set; }
        public Nullable<int> IsDeletedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Password { get; set; }
        public string FatherName { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public string Gender { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Picture { get; set; }
    }
}
