//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineResultCheckPortal
{
    using System;
    
    public partial class GetTokenList_Result3
    {
        public Nullable<long> RowNumber { get; set; }
        public long ID { get; set; }
        public string TokenName { get; set; }
        public string TokenDescription { get; set; }
        public Nullable<int> NumberOfTimeUse { get; set; }
        public string TokenPrice { get; set; }
        public string TokenID { get; set; }
    }
}
