//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineResultCheckPortal
{
    using System;
    
    public partial class GetvalueEndMockExamanation_Result2
    {
        public int ID { get; set; }
        public string RegistrationNumber { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public string ReportCardFile { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> IsDeletedByDate { get; set; }
        public Nullable<int> IsDeletedBy { get; set; }
    }
}
