//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineResultCheckPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManageManagement
    {
        public int ID { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Gender { get; set; }
        public string Photo { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Address { get; set; }
        public string ContactNo { get; set; }
        public string FatherName { get; set; }
        public string DateofBirth { get; set; }
    }
}
