//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineResultCheckPortal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class OnlineResultCheckPortal : DbContext
    {
        public OnlineResultCheckPortal()
            : base("name=OnlineResultCheckPortal")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Academic_Session> Academic_Sessions { get; set; }
        public DbSet<JSCE> JSCEs { get; set; }
        public DbSet<PurchasedToken> PurchasedTokens { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<UsedToken> UsedTokens { get; set; }
        public DbSet<ManageManagement> ManageManagements { get; set; }
        public DbSet<School> Schools { get; set; }
        public DbSet<Token> Tokens { get; set; }
        public DbSet<SchoolName> SchoolNames { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<JSCEResult> JSCEResults { get; set; }
        public DbSet<JSCEDetail> JSCEDetails { get; set; }
        public DbSet<MockExamination> MockExaminations { get; set; }
        public DbSet<MockExamResult> MockExamResults { get; set; }
        public DbSet<EndOfTermExamination> EndOfTermExaminations { get; set; }
        public DbSet<EndOfTermExaminationsResult> EndOfTermExaminationsResults { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<School1> School1 { get; set; }
    
        public virtual ObjectResult<AdminMangement_Result3> AdminMangement()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AdminMangement_Result3>("AdminMangement");
        }
    
        public virtual ObjectResult<EditTokenLists_Result> EditTokenLists(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EditTokenLists_Result>("EditTokenLists", iDParameter);
        }
    
        public virtual ObjectResult<GetTokenList_Result> GetTokenList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTokenList_Result>("GetTokenList");
        }
    
        public virtual ObjectResult<GetDetailsSchool_Result1> GetDetailsSchool()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDetailsSchool_Result1>("GetDetailsSchool");
        }
    
        public virtual ObjectResult<EditSchoolList_Result1> EditSchoolList(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EditSchoolList_Result1>("EditSchoolList", iDParameter);
        }
    
        public virtual ObjectResult<StudentDetails_Result1> StudentDetails(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StudentDetails_Result1>("StudentDetails", userIdParameter);
        }
    
        public virtual ObjectResult<GetSchoolNameDetails_Result> GetSchoolNameDetails(Nullable<int> managementId)
        {
            var managementIdParameter = managementId.HasValue ?
                new ObjectParameter("ManagementId", managementId) :
                new ObjectParameter("ManagementId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSchoolNameDetails_Result>("GetSchoolNameDetails", managementIdParameter);
        }
    
        public virtual ObjectResult<StudentProfile_Result2> StudentProfile(Nullable<int> studentId)
        {
            var studentIdParameter = studentId.HasValue ?
                new ObjectParameter("StudentId", studentId) :
                new ObjectParameter("StudentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StudentProfile_Result2>("StudentProfile", studentIdParameter);
        }
    
        public virtual ObjectResult<GetStudentProfile_Result3> GetStudentProfile()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStudentProfile_Result3>("GetStudentProfile");
        }
    
        public virtual ObjectResult<GetDisplayStudentProfile_Result> GetDisplayStudentProfile(Nullable<int> schoolId)
        {
            var schoolIdParameter = schoolId.HasValue ?
                new ObjectParameter("SchoolId", schoolId) :
                new ObjectParameter("SchoolId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDisplayStudentProfile_Result>("GetDisplayStudentProfile", schoolIdParameter);
        }
    
        public virtual ObjectResult<AdminProfile_Result2> AdminProfile(Nullable<int> adminId)
        {
            var adminIdParameter = adminId.HasValue ?
                new ObjectParameter("AdminId", adminId) :
                new ObjectParameter("AdminId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AdminProfile_Result2>("AdminProfile", adminIdParameter);
        }
    
        public virtual ObjectResult<AdminManageProfile_Result> AdminManageProfile(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AdminManageProfile_Result>("AdminManageProfile", userIdParameter);
        }
    
        public virtual ObjectResult<GetSchoolDetails_Result3> GetSchoolDetails(Nullable<int> managementId)
        {
            var managementIdParameter = managementId.HasValue ?
                new ObjectParameter("ManagementId", managementId) :
                new ObjectParameter("ManagementId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSchoolDetails_Result3>("GetSchoolDetails", managementIdParameter);
        }
    
        public virtual ObjectResult<GetManageJSCEEdit_Result1> GetManageJSCEEdit(Nullable<int> jSCEID)
        {
            var jSCEIDParameter = jSCEID.HasValue ?
                new ObjectParameter("JSCEID", jSCEID) :
                new ObjectParameter("JSCEID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetManageJSCEEdit_Result1>("GetManageJSCEEdit", jSCEIDParameter);
        }
    
        public virtual ObjectResult<GetDisplayManageListJSCE_Result2> GetDisplayManageListJSCE(Nullable<int> createdBy)
        {
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDisplayManageListJSCE_Result2>("GetDisplayManageListJSCE", createdByParameter);
        }
    
        public virtual ObjectResult<AdminUserProfileDisplay_Result19> AdminUserProfileDisplay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AdminUserProfileDisplay_Result19>("AdminUserProfileDisplay");
        }
    
        public virtual ObjectResult<PurchaseToken_Result1> PurchaseToken()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PurchaseToken_Result1>("PurchaseToken");
        }
    
        public virtual ObjectResult<GetJSCEResultEdit_Result2> GetJSCEResultEdit(Nullable<int> jsceId)
        {
            var jsceIdParameter = jsceId.HasValue ?
                new ObjectParameter("JsceId", jsceId) :
                new ObjectParameter("JsceId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetJSCEResultEdit_Result2>("GetJSCEResultEdit", jsceIdParameter);
        }
    
        public virtual ObjectResult<GetUploadResultDetails_Result3> GetUploadResultDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUploadResultDetails_Result3>("GetUploadResultDetails");
        }
    
        public virtual ObjectResult<GetDetailsMockExamanation_Result8> GetDetailsMockExamanation()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDetailsMockExamanation_Result8>("GetDetailsMockExamanation");
        }
    
        public virtual ObjectResult<GetMockExamanationEdit_Result> GetMockExamanationEdit(Nullable<int> mockExamID)
        {
            var mockExamIDParameter = mockExamID.HasValue ?
                new ObjectParameter("MockExamID", mockExamID) :
                new ObjectParameter("MockExamID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMockExamanationEdit_Result>("GetMockExamanationEdit", mockExamIDParameter);
        }
    
        public virtual ObjectResult<GetDetailsEndMockExamanation_Result5> GetDetailsEndMockExamanation()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDetailsEndMockExamanation_Result5>("GetDetailsEndMockExamanation");
        }
    
        public virtual ObjectResult<GetEndMockExamanationEdit_Result> GetEndMockExamanationEdit(Nullable<int> endofTermId)
        {
            var endofTermIdParameter = endofTermId.HasValue ?
                new ObjectParameter("EndofTermId", endofTermId) :
                new ObjectParameter("EndofTermId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEndMockExamanationEdit_Result>("GetEndMockExamanationEdit", endofTermIdParameter);
        }
    
        public virtual ObjectResult<GetOnlyPurchaseTokenResult_Result1> GetOnlyPurchaseTokenResult(string registration, string checkResult)
        {
            var registrationParameter = registration != null ?
                new ObjectParameter("Registration", registration) :
                new ObjectParameter("Registration", typeof(string));
    
            var checkResultParameter = checkResult != null ?
                new ObjectParameter("CheckResult", checkResult) :
                new ObjectParameter("CheckResult", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOnlyPurchaseTokenResult_Result1>("GetOnlyPurchaseTokenResult", registrationParameter, checkResultParameter);
        }
    
        public virtual ObjectResult<string> GetResutFileDownload(string registration, string checkResult)
        {
            var registrationParameter = registration != null ?
                new ObjectParameter("Registration", registration) :
                new ObjectParameter("Registration", typeof(string));
    
            var checkResultParameter = checkResult != null ?
                new ObjectParameter("CheckResult", checkResult) :
                new ObjectParameter("CheckResult", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetResutFileDownload", registrationParameter, checkResultParameter);
        }
    
        public virtual ObjectResult<GetStudentName_Result3> GetStudentName()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStudentName_Result3>("GetStudentName");
        }
    
        public virtual ObjectResult<GetEditMangement_Result9> GetEditMangement(Nullable<int> adminId)
        {
            var adminIdParameter = adminId.HasValue ?
                new ObjectParameter("AdminId", adminId) :
                new ObjectParameter("AdminId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEditMangement_Result9>("GetEditMangement", adminIdParameter);
        }
    
        public virtual ObjectResult<EditUserProfile_Result7> EditUserProfile(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EditUserProfile_Result7>("EditUserProfile", idParameter);
        }
    
        public virtual ObjectResult<CreateSchoolByExcel_Result3> CreateSchoolByExcel(string schoolName)
        {
            var schoolNameParameter = schoolName != null ?
                new ObjectParameter("SchoolName", schoolName) :
                new ObjectParameter("SchoolName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CreateSchoolByExcel_Result3>("CreateSchoolByExcel", schoolNameParameter);
        }
    }
}
