//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineResultCheckPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDownloadResult
    {
        public long ID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string RegitrationNumber { get; set; }
        public string TokenID { get; set; }
        public Nullable<System.DateTime> ResultDownloadDate { get; set; }
        public string ExamTypes { get; set; }
        public string SchoolID { get; set; }
        public Nullable<int> UsedTokenNumber { get; set; }
    }
}
