//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineResultCheckPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsedToken
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> UsedDate { get; set; }
        public Nullable<int> UsedBy { get; set; }
        public Nullable<int> JSCEID { get; set; }
    }
}
