//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineResultCheckPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string StudentID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailID { get; set; }
        public Nullable<short> RoleId { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> IsApprovedBy { get; set; }
        public Nullable<int> IsDeletedBy { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> PurchaseToken { get; set; }
        public Nullable<int> PurchaseTokenBy { get; set; }
        public Nullable<System.DateTime> PurchaseTokenDate { get; set; }
    }
}
